In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv

In [2]:
import os
os.listdir("/kaggle/input")

['datasets']

In [3]:
import os
os.listdir("/kaggle/input/datasets")

['blastchar']

In [4]:
os.listdir("/kaggle/input/datasets/blastchar")

['telco-customer-churn']

In [5]:
os.listdir("/kaggle/input/datasets/blastchar/telco-customer-churn")

['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [6]:
import pandas as pd

path = "/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(path)

df.shape, df.head()

((7043, 21),
    customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
 0  7590-VHVEG  Female              0     Yes         No       1           No
 1  5575-GNVDE    Male              0      No         No      34          Yes
 2  3668-QPYBK    Male              0      No         No       2          Yes
 3  7795-CFOCW    Male              0      No         No      45           No
 4  9237-HQITU  Female              0      No         No       2          Yes

       MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
 0  No phone service             DSL             No  ...               No
 1                No             DSL            Yes  ...              Yes
 2                No             DSL            Yes  ...               No
 3  No phone service             DSL            Yes  ...              Yes
 4                No     Fiber optic             No  ...               No

   TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
 0          No          No              No  Month-to-month              Yes
 1          No          No              No        One year               No
 2          No          No              No  Month-to-month              Yes
 3         Yes          No              No        One year               No
 4          No          No              No  Month-to-month              Yes

                PaymentMethod MonthlyCharges  TotalCharges Churn
 0           Electronic check          29.85         29.85    No
 1               Mailed check          56.95        1889.5    No
 2               Mailed check          53.85        108.15   Yes
 3  Bank transfer (automatic)          42.30       1840.75    No
 4           Electronic check          70.70        151.65   Yes

 [5 rows x 21 columns])

In [7]:
df["Churn"].value_counts(normalize=True)
df.isna().mean().sort_values(ascending=False).head(15)
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [8]:
df.shape
df["Churn"].value_counts(normalize=True)
df.isna().mean().sort_values(ascending=False).head(15)

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
dtype: float64

In [9]:
import pandas as pd

path = "/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(path)

df.shape

(7043, 21)

In [10]:
import numpy as np

df["churn"] = (df["Churn"] == "Yes").astype(int)
(df["churn"].mean() * 100).round(2)

np.float64(26.54)

In [11]:
(df.groupby("Contract")["churn"].mean()*100).round(2).sort_values(ascending=False)

Contract
Month-to-month    42.71
One year          11.27
Two year           2.83
Name: churn, dtype: float64

In [12]:
df["tenure_bin"] = pd.cut(df["tenure"], bins=[0, 6, 12, 24, 48, 72], include_lowest=True)
(df.groupby("tenure_bin")["churn"].mean()*100).round(2)

/tmp/ipykernel_16/3646826670.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  (df.groupby("tenure_bin")["churn"].mean()*100).round(2)

tenure_bin
(-0.001, 6.0]    52.94
(6.0, 12.0]      35.89
(12.0, 24.0]     28.71
(24.0, 48.0]     20.39
(48.0, 72.0]      9.51
Name: churn, dtype: float64

In [13]:
df["mc_bin"] = pd.qcut(df["MonthlyCharges"], q=4)
(df.groupby("mc_bin")["churn"].mean()*100).round(2)

/tmp/ipykernel_16/3645265403.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  (df.groupby("mc_bin")["churn"].mean()*100).round(2)

mc_bin
(18.249, 35.5]     11.24
(35.5, 70.35]      24.58
(70.35, 89.85]     37.51
(89.85, 118.75]    32.88
Name: churn, dtype: float64

In [14]:
# 1) convertir TotalCharges a numérico
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# 2) ver cuántos NaN quedaron por la conversión
df["TotalCharges"].isna().mean()

# 3) opción simple: imputar con mediana
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())

In [15]:
df.shape
df["TotalCharges"].head(10)
df["TotalCharges"].dtype

dtype('float64')

In [16]:
import pandas as pd
import numpy as np

# Convertir a string, limpiar espacios raros y convertir a número
tc = df["TotalCharges"].astype(str).str.strip()
tc = tc.replace({"": np.nan, " ": np.nan, "nan": np.nan})

df["TotalCharges"] = pd.to_numeric(tc, errors="coerce")

# Revisar % de NaN
df["TotalCharges"].isna().mean()

np.float64(0.0)

In [17]:
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())
df["TotalCharges"].isna().sum()

np.int64(0)

In [18]:
from sklearn.model_selection import train_test_split

# target
y = (df["Churn"] == "Yes").astype(int)

# features (quitamos target y el ID)
X = df.drop(columns=["Churn", "customerID"], errors="ignore")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((5634, 22), (1409, 22))

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# columnas por tipo
num_cols = X.select_dtypes(include=["number"]).columns
cat_cols = X.select_dtypes(exclude=["number"]).columns

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
        ("cat", categorical_transformer, cat_cols),
    ]
)

clf = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", LogisticRegression(max_iter=2000))
])

clf.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'churn'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'tenure_bin', 'mc_bin'],
      dtype='object'))])),
                ('model', LogisticRegression(max_iter=2000))])

In [20]:
from sklearn.metrics import roc_auc_score, f1_score, classification_report

proba = clf.predict_proba(X_test)[:, 1]
pred = (proba >= 0.5).astype(int)

roc = roc_auc_score(y_test, proba)
f1 = f1_score(y_test, pred)

roc, f1

(np.float64(1.0), 1.0)

In [21]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1035
           1       1.00      1.00      1.00       374

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409

In [22]:
for thr in [0.3, 0.4, 0.5]:
    pred_thr = (proba >= thr).astype(int)
    print(thr, "F1:", round(f1_score(y_test, pred_thr), 3))

0.3 F1: 1.0
0.4 F1: 1.0
0.5 F1: 1.0

In [23]:
X.columns[X.columns.str.contains("churn", case=False, regex=True)]

Index(['churn'], dtype='object')

In [24]:
from sklearn.model_selection import train_test_split

y = (df["Churn"] == "Yes").astype(int)

cols_to_drop = ["Churn", "churn", "customerID", "tenure_bin", "mc_bin"]
X = df.drop(columns=cols_to_drop, errors="ignore")

# guardrail pro (si falla, hay fuga)
assert "churn" not in X.columns and "Churn" not in X.columns

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((5634, 19), (1409, 19))

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, f1_score, classification_report

num_cols = X.select_dtypes(include=["number"]).columns
cat_cols = X.select_dtypes(exclude=["number"]).columns

preprocess = ColumnTransformer([
    ("num", Pipeline([("imp", SimpleImputer(strategy="median"))]), num_cols),
    ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")),
                      ("oh", OneHotEncoder(handle_unknown="ignore"))]), cat_cols),
])

clf = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=2000))
])

clf.fit(X_train, y_train)

proba = clf.predict_proba(X_test)[:, 1]
pred = (proba >= 0.5).astype(int)

roc = roc_auc_score(y_test, proba)
f1 = f1_score(y_test, pred)

roc, f1, print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.56      0.61       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(np.float64(0.842178821462709), 0.6060606060606061, None)

In [26]:
from sklearn.linear_model import LogisticRegression

clf = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=5000, class_weight="balanced"))
])

In [27]:
from sklearn.linear_model import LogisticRegression

clf_bal = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=5000, class_weight="balanced"))
])

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, f1_score, classification_report

In [29]:
clf_bal = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=5000, class_weight="balanced"))
])

In [30]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, f1_score, classification_report

# Target
y = (df["Churn"] == "Yes").astype(int)

# Features (evitar leakage y columnas auxiliares)
cols_to_drop = ["Churn", "churn", "customerID", "tenure_bin", "mc_bin"]
X = df.drop(columns=cols_to_drop, errors="ignore")

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Columnas por tipo
num_cols = X.select_dtypes(include=["number"]).columns
cat_cols = X.select_dtypes(exclude=["number"]).columns

# Preprocess (aquí se crea preprocess, que es lo que te falta)
numeric_transformer = Pipeline([
    ("imp", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline([
    ("imp", SimpleImputer(strategy="most_frequent")),
    ("oh", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", numeric_transformer, num_cols),
    ("cat", categorical_transformer, cat_cols),
])

# Modelo BALANCED
clf_bal = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter=5000, class_weight="balanced"))
])

clf_bal.fit(X_train, y_train)

proba_bal = clf_bal.predict_proba(X_test)[:, 1]
pred_bal = (proba_bal >= 0.5).astype(int)

roc_bal = roc_auc_score(y_test, proba_bal)
f1_bal = f1_score(y_test, pred_bal)

print("ROC_AUC:", roc_bal)
print("F1:", f1_bal)
print(classification_report(y_test, pred_bal))

ROC_AUC: 0.841558810612519
F1: 0.6157068062827226
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

In [31]:
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score

rows = []
for thr in np.arange(0.2, 0.81, 0.05):
    pred_thr = (proba_bal >= thr).astype(int)
    rows.append({
        "thr": round(thr, 2),
        "precision": round(precision_score(y_test, pred_thr), 3),
        "recall": round(recall_score(y_test, pred_thr), 3),
        "f1": round(f1_score(y_test, pred_thr), 3),
    })
pd.DataFrame(rows)

     thr  precision  recall     f1
0   0.20      0.389   0.963  0.554
1   0.25      0.409   0.939  0.570
2   0.30      0.429   0.928  0.587
3   0.35      0.447   0.904  0.598
4   0.40      0.466   0.866  0.606
5   0.45      0.485   0.840  0.614
6   0.50      0.506   0.786  0.616
7   0.55      0.524   0.751  0.618
8   0.60      0.541   0.706  0.613
9   0.65      0.567   0.666  0.613
10  0.70      0.600   0.602  0.601
11  0.75      0.660   0.508  0.574
12  0.80      0.708   0.396  0.508

In [32]:
import numpy as np
import pandas as pd

rows = []
for thr in np.arange(0.2, 0.81, 0.05):
    pred_thr = (proba_bal >= thr).astype(int)
    rows.append({
        "thr": round(thr, 2),
        "predicted_churn_rate": round(pred_thr.mean(), 3),  # % marcado como churn
    })

pd.DataFrame(rows)

     thr  predicted_churn_rate
0   0.20                 0.656
1   0.25                 0.609
2   0.30                 0.573
3   0.35                 0.537
4   0.40                 0.493
5   0.45                 0.460
6   0.50                 0.412
7   0.55                 0.380
8   0.60                 0.346
9   0.65                 0.312
10  0.70                 0.266
11  0.75                 0.204
12  0.80                 0.148

In [33]:
THR = 0.70  # o 0.55

eval_df = X_test.copy()
eval_df["y_true"] = y_test.values
eval_df["proba"] = proba_bal
eval_df["y_pred"] = (proba_bal >= THR).astype(int)

# Falsos Negativos: eran churn (1) pero predijo no churn (0) -> churners que se te escapan
fn = eval_df[(eval_df.y_true==1) & (eval_df.y_pred==0)].sort_values("proba", ascending=False)

# Falsos Positivos: no eran churn (0) pero predijo churn (1) -> contactos “innecesarios”
fp = eval_df[(eval_df.y_true==0) & (eval_df.y_pred==1)].sort_values("proba", ascending=False)

# columnas útiles para entender patrones (ajusta si alguna no existe)
cols = [c for c in ["Contract","tenure","MonthlyCharges","TotalCharges","InternetService",
                    "TechSupport","OnlineSecurity","PaperlessBilling","PaymentMethod","proba"]
        if c in eval_df.columns]

fn.head(10)[cols], fp.head(10)[cols]

(            Contract  tenure  MonthlyCharges  TotalCharges InternetService  \
 3007  Month-to-month      32           74.40       2276.95     Fiber optic
 4651  Month-to-month      15           86.20       1270.20     Fiber optic
 5091  Month-to-month       6           30.50        208.70             DSL
 5728  Month-to-month      13           89.40       1132.35     Fiber optic
 3251  Month-to-month      37          106.75       4056.75     Fiber optic
 3737  Month-to-month       5           50.60        249.95             DSL
 3350  Month-to-month       1           44.15         44.15             DSL
 3287        One year      19          100.95       1875.55     Fiber optic
 1644  Month-to-month      34          109.80       3587.25     Fiber optic
 5787  Month-to-month      36           87.55       3078.10     Fiber optic

      TechSupport OnlineSecurity PaperlessBilling              PaymentMethod  \
 3007          No             No              Yes           Electronic check
 4651          No            Yes               No           Electronic check
 5091          No             No              Yes    Credit card (automatic)
 5728         Yes             No               No           Electronic check
 3251          No            Yes              Yes  Bank transfer (automatic)
 3737          No             No              Yes               Mailed check
 3350          No             No              Yes               Mailed check
 3287         Yes             No              Yes           Electronic check
 1644          No            Yes              Yes               Mailed check
 5787         Yes             No              Yes           Electronic check

          proba
 3007  0.697747
 4651  0.696703
 5091  0.695878
 5728  0.694704
 3251  0.686275
 3737  0.683182
 3350  0.680018
 3287  0.679473
 1644  0.673543
 5787  0.672658  ,
             Contract  tenure  MonthlyCharges  TotalCharges InternetService  \
 3346  Month-to-month       2           84.05        186.05     Fiber optic
 4039  Month-to-month       7           94.10        701.30     Fiber optic
 935   Month-to-month       4           83.25        308.05     Fiber optic
 5019  Month-to-month      14           95.60       1273.30     Fiber optic
 352   Month-to-month       7           89.15        574.35     Fiber optic
 2519  Month-to-month       2           91.45        171.45     Fiber optic
 2350  Month-to-month       5           84.00        424.75     Fiber optic
 6574  Month-to-month       9           90.10        816.80     Fiber optic
 5627  Month-to-month       7           74.85        485.25     Fiber optic
 5839  Month-to-month       7           75.40        533.05     Fiber optic

      TechSupport OnlineSecurity PaperlessBilling     PaymentMethod     proba
 3346          No             No              Yes  Electronic check  0.920628
 4039          No             No              Yes  Electronic check  0.918090
 935           No             No              Yes  Electronic check  0.916793
 5019          No             No              Yes  Electronic check  0.910452
 352           No             No              Yes  Electronic check  0.906750
 2519          No             No              Yes  Electronic check  0.900001
 2350          No             No              Yes  Electronic check  0.898644
 6574          No             No              Yes  Electronic check  0.895521
 5627          No             No              Yes  Electronic check  0.887726
 5839          No             No              Yes  Electronic check  0.887165  )

In [34]:
fn["Contract"].value_counts(normalize=True).head(5), fp["Contract"].value_counts(normalize=True).head(5)

(Contract
 Month-to-month    0.704698
 One year          0.234899
 Two year          0.060403
 Name: proportion, dtype: float64,
 Contract
 Month-to-month    0.986667
 One year          0.013333
 Name: proportion, dtype: float64)